// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBli9yx0t3FiR-0pYN9I058t_biNborZmc',
    appId: '1:1098390700532:web:93266e1b8b322e1ca9b9a1',
    messagingSenderId: '1098390700532',
    projectId: 'garduation-project-5d180',
    authDomain: 'garduation-project-5d180.firebaseapp.com',
    storageBucket: 'garduation-project-5d180.appspot.com',
    measurementId: 'G-SG4WCJ8VQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBst-5ZuAt77tuhqcsWFnQqQmaaEDjWOaY',
    appId: '1:1098390700532:android:14a1bfa46aed0a44a9b9a1',
    messagingSenderId: '1098390700532',
    projectId: 'garduation-project-5d180',
    storageBucket: 'garduation-project-5d180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfdrPszVPwp1wzHqm45uPtOANFt_ZdmtE',
    appId: '1:1098390700532:ios:4ccf4820d45e1376a9b9a1',
    messagingSenderId: '1098390700532',
    projectId: 'garduation-project-5d180',
    storageBucket: 'garduation-project-5d180.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfdrPszVPwp1wzHqm45uPtOANFt_ZdmtE',
    appId: '1:1098390700532:ios:f3b7a61e37c85c6ba9b9a1',
    messagingSenderId: '1098390700532',
    projectId: 'garduation-project-5d180',
    storageBucket: 'garduation-project-5d180.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
